apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: integration-dev
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306    
      targetPort: 3306 
      nodePort: 32306  
  type: NodePort
