apiVersion: v1
kind: Service
metadata:
  name: ignite
spec:
  selector:
    app: ignite
  ports:
    - name: client-port
      protocol: TCP
      port: 10800
      targetPort: 10800
    - name: communication-port-1
      protocol: TCP
      port: 47500
      targetPort: 47500
    - name: communication-port-2
      protocol: TCP
      port: 47501
      targetPort: 47501
  type: ClusterIP
