apiVersion: v1
kind: Service
metadata:
  name: artemis-service
spec:
  selector:
    app: artemis
  ports:
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
      nodePort: 31861
    - name: mq
      protocol: TCP
      port: 61616
      targetPort: 61616
      nodePort: 31616
  type: NodePort
