apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: integration-dev
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432    
      targetPort: 5432 
      nodePort: 32432  
  type: NodePort
