services:
  hl7-file-output-route:
    build: .
    image: hl7-file-output-route:latest
    environment:
      MYSQL_HOST_IP: ${MYSQL_HOST_IP}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER_NAME: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ACTIVEMQ_HOST_IP: ${ACTIVEMQ_HOST_IP}
      ACTIVEMQ_PORT: ${ACTIVEMQ_PORT}
      ACTIVEMQ_USER_NAME: ${ACTIVEMQ_USER_NAME}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      IGNITE_HOST: ${IGNITE_HOST}
      IGNITE_PORT: ${IGNITE_PORT}
      SMB_OUTBOUND_ADAPTER_SAMBA_USER: ${SMB_OUTBOUND_ADAPTER_SAMBA_USER}
      SMB_OUTBOUND_ADAPTER_SAMBA_PASSWORD: ${SMB_OUTBOUND_ADAPTER_SAMBA_PASSWORD}
      JAVA_OPTS: >-
        -Djcifs.smb.client.enableSMB1=true
        -Djcifs.smb.client.disableSMB2=true
    networks:
      - backend
      - integration-net
    volumes:
      - ${HL7_FILE_OUTPUT_ROUTE_CONFIG_FILE}:/app/route-config.json

networks:
  backend:
    driver: bridge

  integration-net:
    external: true