version: '3.8'

services:
  hl7-file-output-route:
    build: .
    image: hl7-file-output-route
    environment:
      MYSQL_HOST_IP: ${MYSQL_HOST_IP}
      MYSQL_USER_NAME: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ACTIVEMQ_HOST_IP: ${ACTIVEMQ_HOST_IP}
      ACTIVEMQ_USER_NAME: ${ACTIVEMQ_USER_NAME}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      IGNITE_HOST_IP: ${IGNITE_HOST_IP}
      INTEGRATION_CONFIG_FILE: ${HL7_FILE_OUTPUT_ROUTE_CONFIG_FILE}
    networks:
      - backend
    volumes:
      - ${INTEGRATION_CONFIG_FILE}:/app/route-config.json

networks:
  backend:
    driver: bridge