services:
  integration-rest:
    build: .
    image: integration-rest:latest
    environment:
      MYSQL_HOST_IP: ${MYSQL_HOST_IP}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER_NAME: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ACTIVEMQ_HOST_IP: ${ACTIVEMQ_HOST_IP}
      ACTIVEMQ_PORT: ${ACTIVEMQ_PORT}
      ACTIVEMQ_USER_NAME: ${ACTIVEMQ_USER_NAME}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      IGNITE_HOST: ${IGNITE_HOST}
      IGNITE_PORT: ${IGNITE_PORT}
    ports:
      - "9999:8080"
    networks:
      - backend
      - integration-net

networks:
  backend:
    driver: bridge

  integration-net:
    external: true

