services:
  mllp-output-route:
    build: .
    image: mllp-output-route:latest
    environment:
      POSTGRES_HOST_IP: ${POSTGRES_HOST_IP}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER_NAME: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ACTIVEMQ_HOST_IP: ${ACTIVEMQ_HOST_IP}
      ACTIVEMQ_PORT: ${ACTIVEMQ_PORT}
      ACTIVEMQ_USER_NAME: ${ACTIVEMQ_USER_NAME}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      IGNITE_HOST: ${IGNITE_HOST}
      IGNITE_PORT: ${IGNITE_PORT}
    networks:
      - backend
      - integration-net
    volumes:
      - ${MLLP_OUTPUT_ROUTE_CONFIG_FILE}:/app/route-config.json

networks:
  backend:
    driver: bridge

  integration-net:
    external: true
