version: '3.8'

services:
  mllp-output-route:
    build: .
    image: mllp-output-route:latest
    environment:
      MYSQL_HOST_IP: ${MYSQL_HOST_IP}
      MYSQL_USER_NAME: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ACTIVEMQ_HOST_IP: ${ACTIVEMQ_HOST_IP}
      ACTIVEMQ_USER_NAME: ${ACTIVEMQ_USER_NAME}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      IGNITE_HOST: ${IGNITE_HOST}
      IGNITE_PORT: ${IGNITE_PORT}
    networks:
      - backend
      - integration-net
    volumes:
      - ${MLLP_OUTPUT_ROUTE_CONFIG_FILE}:/app/route-config.json

networks:
  backend:
    driver: bridge

  integration-net:
    external: true
