apiVersion: apps/v1
kind: Deployment
metadata:
  name: hl7-file-output-route
  namespace: integration-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hl7-file-output-route
  template:
    metadata:
      labels:
        app: hl7-file-output-route
    spec:
      containers:
        - name: hl7-file-output-route
          image: hl7-file-output-route:latest
          imagePullPolicy: IfNotPresent
          env:
            # MySQL
            - name: POSTGRES_HOST_IP
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER_NAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            # ActiveMQ
            - name: ACTIVEMQ_HOST_IP
              value: artemis-service
            - name: ACTIVEMQ_PORT
              value: "61616"
            - name: ACTIVEMQ_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: activemq-secret
                  key: ACTIVEMQ_USER_NAME
            - name: ACTIVEMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: activemq-secret
                  key: ACTIVEMQ_PASSWORD

            # Ignite
            - name: IGNITE_HOST
              value: ignite-node
            - name: IGNITE_PORT
              value: "10800"
                  
            # Samba
            - name: SMB_OUTBOUND_ADAPTER_SAMBA_USER
              valueFrom:
                secretKeyRef:
                  name: smb-outbound-secret
                  key: SMB_OUTBOUND_ADAPTER_SAMBA_USER
            - name: SMB_OUTBOUND_ADAPTER_SAMBA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smb-outbound-secret
                  key: SMB_OUTBOUND_ADAPTER_SAMBA_PASSWORD

            # Route config path
            - name: HL7_FILE_INPUT_CONFIG_FILE
              value: /app/route-config.json

          volumeMounts:
            - name: config-volume
              mountPath: /app/route-config.json
              subPath: config_file

      volumes:
        - name: config-volume
          configMap:
            name: hl7-file-output-route-config
