apiVersion: v1
kind: Service
metadata:
  name: mllp-input-route
spec:
  selector:
    app: mllp-input-route
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30888  
  type: NodePort
