version: '3.8'

services:
  mysql:
    build:
      context: .
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: integration
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ${INIT_DIR}:/docker-entrypoint-initdb.d
    networks:
      - integration-net
    restart: always

networks:
  integration-net:
    external: true

volumes:
  mysql-data:
