services:
  mllp-input-route:
    build: .
    image: mllp-input-route:latest
    environment:
      MYSQL_HOST_IP: ${MYSQL_HOST_IP}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER_NAME: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ACTIVEMQ_HOST_IP: ${ACTIVEMQ_HOST_IP}
      ACTIVEMQ_PORT: ${ACTIVEMQ_PORT}
      ACTIVEMQ_USER_NAME: ${ACTIVEMQ_USER_NAME}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      IGNITE_HOST: ${IGNITE_HOST}
      IGNITE_PORT: ${IGNITE_PORT}
    ports:
      - "8888:8888"
    networks:
      - backend
      - integration-net
    volumes:
      - ${MLLP_INPUT_ROUTE_CONFIG_FILE}:/app/route-config.json

networks:
  backend:
    driver: bridge

  integration-net:
    external: true

