apiVersion: v1
kind: Service
metadata:
  name: integration-rest
spec:
  selector:
    app: integration-rest
  ports:
    - name: http
      port: 9999         # external port used inside the cluster
      targetPort: 8080   # container port
      nodePort: 30999 
      protocol: TCP
  type: NodePort
