services:
  hl7-file-input-route:
    build: .
    image: hl7-file-input-route:latest
    environment:
      MYSQL_HOST_IP: ${MYSQL_HOST_IP}
      MYSQL_USER_NAME: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ACTIVEMQ_HOST_IP: ${ACTIVEMQ_HOST_IP}
      ACTIVEMQ_USER_NAME: ${ACTIVEMQ_USER_NAME}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      SMB_USER_NAME: ${SMB_INBOUND_ADAPTER_SAMBA_USER}
      SMB_PASSWORD: ${SMB_INBOUND_ADAPTER_SAMBA_PASSWORD}
      IGNITE_HOST: ${IGNITE_HOST}
      IGNITE_PORT: ${IGNITE_PORT}
      JAVA_OPTS: >-
        -Djcifs.smb.client.enableSMB1=false
        -Djcifs.smb.client.enableSMB2=true
        -Djcifs.smb.client.enableSMB3=true
    networks:
      - backend
      - integration-net
    volumes:
      - ${HL7_FILE_INPUT_ROUTE_CONFIG_FILE}:/app/route-config.json

networks:
  backend:
    driver: bridge

  integration-net:
    external: true