services:
  hl7-file-input-route:
    build: .
    image: hl7-file-input-route:latest
    environment:
      POSTGRES_HOST_IP: ${POSTGRES_HOST_IP}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER_NAME: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ACTIVEMQ_HOST_IP: ${ACTIVEMQ_HOST_IP}
      ACTIVEMQ_PORT: ${ACTIVEMQ_PORT}
      ACTIVEMQ_USER_NAME: ${ACTIVEMQ_USER_NAME}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      IGNITE_HOST: ${IGNITE_HOST}
      IGNITE_PORT: ${IGNITE_PORT}
      SMB_INBOUND_ADAPTER_SAMBA_USER: ${SMB_INBOUND_ADAPTER_SAMBA_USER}
      SMB_INBOUND_ADAPTER_SAMBA_PASSWORD: ${SMB_INBOUND_ADAPTER_SAMBA_PASSWORD}
      JAVA_OPTS: >-
        -Djcifs.smb.client.enableSMB1=false
        -Djcifs.smb.client.enableSMB2=true
        -Djcifs.smb.client.enableSMB3=true
    networks:
      - backend
      - integration-net
    volumes:
      - ${HL7_FILE_INPUT_ROUTE_CONFIG_FILE}:/app/route-config.json

networks:
  backend:
    driver: bridge

  integration-net:
    external: true