version: '3.8'

services:
  hl7-file-input-route:
    build: .
    image: hl7-file-input-route
    environment:
      MYSQL_HOST_IP: ${MYSQL_HOST_IP}
      MYSQL_USER_NAME: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ACTIVEMQ_HOST_IP: ${ACTIVEMQ_HOST_IP}
      ACTIVEMQ_USER_NAME: ${ACTIVEMQ_USER_NAME}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      IGNITE_HOST: ${IGNITE_HOST}
      IGNITE_PORT: ${IGNITE_PORT}
    networks:
      - backend
      - integration-net
    volumes:
      - ${HL7_FILE_INPUT_ROUTE_CONFIG_FILE}:/app/route-config.json
      - /c/dev/NE/file-in:/app/host-files/in

networks:
  backend:
    driver: bridge

  integration-net:
    external: true