services:
  postgres:
    build: .
    image: integration-postgres:latest
    environment:
      POSTGRES_DB: integration
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - integration-net
    restart: always

networks:
  integration-net:
    external: true

volumes:
  postgres-data:
