FROM vromero/activemq-artemis

# Copy custom broker configuration
COPY broker.xml /var/lib/artemis/etc/

# Set correct permissions
USER root

RUN chmod 644 /var/lib/artemis/etc/broker.xml

USER artemis
CMD ["/var/lib/artemis/bin/artemis", "run"]
 
